Added unit test for comment and post model.
2011-fakebook-project3/posts pull request #135
Opened 2021-04-01 22:22 UTC by DamionSilver

Originally, unit testing was mistaken for integration testing. We switched the directories, and we realized we had no unit testing for the business logic. We implemented Unit testing for the comment and post models inside the unit testing directory.

2021-04-01 22:43 UTC, escalonn requested changes
implementing behavior and tests is supposed to be done in separate tdd-fail and tdd-pass pull requests to a feature branch, not all together in one PR to main branch.

2021-04-01 22:43 UTC, escalonn commented on Fakebook.Posts/Fakebook.Posts.Domain/Models/Comment.cs
> +        private string _Content;
keep consistent with project naming convention - private fields should start with underscore and lowercase letter

2021-04-01 22:43 UTC, escalonn commented on Fakebook.Posts/Fakebook.Posts.Domain/Models/Comment.cs
> +                    throw new ArgumentException("A correct email format is required.");
use the parameter name argument with argumentexception as well - nameof(value) in the case of a property setter like this.
check against null first as well with argumentnullexception.
i guess it's fine to move the validation out of the constructor into the property setters, but do the setters need to be public? i guess for the content, sure, we could edit that. but the user email?

2021-04-01 22:43 UTC, escalonn commented on Fakebook.Posts/Fakebook.Posts.UnitTests/PostTests.cs
> +                Assert.NotNull(newcomment.UserEmail);
weird indentation throughout this PR. stick to the preexisting style. it's easy, every editor has a command for it

2021-04-02 00:14 UTC, escalonn requested changes
this is not following our tdd process. check with team lead.

2021-04-02 00:14 UTC, escalonn commented on Fakebook.Posts/Fakebook.Posts.Domain/Models/Comment.cs
> +
this exception doesnt make sense.
and the whitespace being added above should not be there

2021-04-02 00:14 UTC, escalonn commented on Fakebook.Posts/Fakebook.Posts.Domain/Models/Post.cs
> +
this exception doesnt make sense

2021-04-02 00:14 UTC, escalonn commented on Fakebook.Posts/Fakebook.Posts.IntegrationTests/Controllers/DeleteCommentTests.cs
> +namespace Fakebook.Posts.IntegrationTests.Controllers
this branch has unrelated changes in it from a different pull request. that's a result of either where this branch was started from, or maybe where you merged into it from. two general solutions to that kind of problem - extricate those changes from this branch, which can have some pitfalls to it, or, this branch just has to wait until the other branch is merged, at which point these changes will disappear from the perspective of the PR.

2021-04-02 01:18 UTC, nosyrbllewe commented
Created new branch and pull request: https://github.com/2011-fakebook-project3/posts/pull/138

2021-04-02 01:18 UTC, closed without merging